export const REACT_APP_LOGIN_USER = process.env.REACT_APP_LOGIN_USER;
export const REACT_APP_VERIFY_USER = process.env.REACT_APP_VERIFY_USER;
export const REACT_APP_LOGOUT_USER = process.env.REACT_APP_LOGOUT_USER;

export const REACT_APP_LOGIN_REDIRECT_URL = process.env.REACT_APP_LOGIN_REDIRECT_URL;
export const REACT_APP_MEMBERSHIP_REDIRECT_URL = process.env.REACT_APP_MEMBERSHIP_REDIRECT_URL;
export const REACT_APP_COOKIE1 = process.env.REACT_APP_COOKIE1;
export const REACT_APP_COOKIE2 = process.env.REACT_APP_COOKIE2;
